### ISSUE TITLE
Want to add another parameter to the model but there's an error

### ISSUE THREAD

**Issue by ch1tsss** [JakeKandell/NBA-Predict#1]
Hi! I'm new here in github and python

![image](https://user-images.githubusercontent.com/59005211/71320439-495b0000-24e6-11ea-893e-160da147c856.png)

How can I edit this? Should I just put the parameter? If I do so, an error occurs

![image](https://user-images.githubusercontent.com/59005211/71320449-6db6dc80-24e6-11ea-9d78-4a54677108a2.png)

Thanks in advance!

**Comment by JakeKandell** [comment]
The error is occurring is due to the fact that the data included in this repository only has data on those seven specific stats. When you only add a feature right there, you're saying that there are eight categories that you want to analyze, but the data being supplied has just seven categories. If you want to add a new statistic, you will have to change a few other places so that you first scrape a new set of data and then create a model with the new data. Let me know if you need me to show you how to do that.
