### ISSUE TITLE
CreateModel problem

### ISSUE THREAD

**Issue by YHHuan** [JakeKandell/NBA-Predict#19]
Hi I was planning to create a model for season 2019-20 and a few problems occurs to me:
1.
![image](https://user-images.githubusercontent.com/90615883/198295937-07ba41b7-3b67-4d53-9b97-b43dc008bbdc.png)
this seems like the API didn't fetch any data and the [0] is out of range. Is it I accidently tuned anything wrong?

2. The following is the definition of createmodel:
createModel(startYear=2019, startMonth=10, startDay=24, endYear=2020, endMonth=10,
            endDay=11, season='2019-20', startOfSeason='10/22/2019', filename='2019_20model.pkl')

I'm wondering what does start and end date means. If it's the range I'd like to train, will it be from 2016~2018 if I want to use the combined data in the package? Then what's the meaning of startofseason?

Thanks!

**Comment by 228lebron** [comment]
yeah, i got same error

**Comment by JakeKandell** [comment]
It has been a while since I have updated this repo, so I'm not 100%. One thing I would try is setting the startDay to the 25th. It should always be at least three days after the season starts to be safe. It's also possible that the api has changed since I created this project.

The start and end date represent the data that you would like to train and test the model on. startOfSeason should just be the first date of games for the year that you are getting data from. 

When you call create model you have two options. You can specify the specific dates that you want to use to train the model. Or, you can use the csv file I provided that has the data for three years from 2016-2018. If you use the combined data I provided, the start date and end date don't matter because they aren't used. You should comment out the lines in createModel.py that don't apply to your use case.

Let me know if you need further clarification.
