### ISSUE TITLE
Updating the database 

### ISSUE THREAD

**Issue by Maxlanglet** [JakeKandell/NBA-Predict#9]
Hey! awesome work btw! I was wondering if there's a way to update the database since I think it is bound to the seasons from 2016 to 2019 if I'm not mistaken ? 

Plus I had a question when creating a new model, what is taken into account ? what changes ? Imagine a month from now I want a new model that would take into account the present performances of a team, I just need to specify the dates in the createModel() function ? Or the database also need to be updated ? Is there a function in your code that does that automatically ? 

Thanks in advance!

**Comment by JakeKandell** [comment]
So the database was only used to train the model. All this did was adjust how much each stat is weighted when the stats of both teams are compared. 

When the predictions happen, the model grabs the latest stats for each team and then adjusts them based on the weights determined when the model was trained. Therefore, the present performance of the teams are always taken into account. The team specific data from the database is not considered at all.

Creating a new model isn't necessary because the way that NBA teams play has not changed drastically since 2016, so the weights applied to each stat would likely be similar no matter what set of games you train the model on. 

Let me know if you still have questions.
